runtime: nodejs22
service: default

handlers:
  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  - url: /assets
    static_dir: dist/assets

  - url: /(.*\.(gif|png|jpg|jpeg|svg))$
    static_files: dist/\1
    upload: dist/(.*\.(gif|png|jpg|jpeg|svg))$